/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "renserve",
  "description": "程序相关知识整理，归纳，总结",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "前端博客,个人技术博客,前端,前端开发,前端框架,web前端,前端面试题,技术文档,学习,面试,JavaScript,js,ES6,TypeScript,vue,python,css3,html5,Node,git,github,markdown"
      }
    ],
    [
      "meta",
      {
        "name": "baidu-site-verification",
        "content": "7F55weZDDc"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#11a8cd"
      }
    ],
    [
      "script",
      {
        "data-ad-client": "ca-pub-7828333725993554",
        "async": "async",
        "src": "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "前端",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "01.前端",
            "imgUrl": "/img/front.jpg",
            "description": "前端常用代码整理"
          }
        },
        "title": "前端",
        "date": "2021-06-29T11:51:53.000Z",
        "permalink": "/front",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/01.%E5%89%8D%E7%AB%AF.html",
      "relativePath": "00.目录页/01.前端.md",
      "key": "v-67658c13",
      "path": "/front/",
      "lastUpdated": "2022/01/01, 01:19:17",
      "headersStr": null,
      "content": "",
      "normalizedContent": "",
      "charsets": {}
    },
    {
      "title": "网站",
      "frontmatter": {
        "title": "网站",
        "date": "2021-06-29T18:48:15.000Z",
        "permalink": "/pages/a8a2c8/",
        "article": false
      },
      "regularPath": "/08.%E6%94%B6%E8%97%8F/01.%E7%BD%91%E7%AB%99.html",
      "relativePath": "08.收藏/01.网站.md",
      "key": "v-5af2c716",
      "path": "/pages/a8a2c8/",
      "headers": [
        {
          "level": 2,
          "title": "精选知识库",
          "slug": "精选知识库",
          "normalizedTitle": "精选知识库",
          "charIndex": 2
        },
        {
          "level": 2,
          "title": "Web文档",
          "slug": "web文档",
          "normalizedTitle": "web文档",
          "charIndex": 540
        },
        {
          "level": 2,
          "title": "博客收录",
          "slug": "博客收录",
          "normalizedTitle": "博客收录",
          "charIndex": 778
        }
      ],
      "lastUpdated": "2022/01/01, 01:19:17",
      "headersStr": "精选知识库 Web文档 博客收录",
      "content": "# 精选知识库\n\nawesome-bookmarks\n\n个人收藏夹\n\n阮一峰的网络日志\n\n较为详细的前端知识教程\n\n- name: awesome-bookmarks\n  desc: 个人收藏夹\n  avatar: https://panjiachen.github.io/awesome-bookmarks/home.jpg # 可选\n  link: https://panjiachen.github.io/awesome-bookmarks/ # 可选\n  bgColor: '#DCF4FF' # 可选，默认var(--bodyBg)。颜色值有#号时请添加单引号\n  textColor: '#6854A1' # 可选，默认var(--textColor)\n- name: 阮一峰的网络日志\n  desc: '较为详细的前端知识教程'\n  avatar: https://www.ruanyifeng.com/favicon.ico\n  link: https://www.ruanyifeng.com/blog/\n  bgColor: '#DCF4FF'\n  textColor: '#6854A1'\n\n\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n\n\n\n# Web文档\n\nMDN\n\nWeb技术权威文档\n\n- name: MDN\n  desc: 'Web技术权威文档'\n  avatar: https://developer.mozilla.org/favicon-48x48.97046865.png\n  link: https://developer.mozilla.org/zh-CN/docs/Web\n  bgColor: '#FAFAFA'\n  textColor: '#666666'\n\n\n1\n2\n3\n4\n5\n6\n\n\n\n# 博客收录\n\nEvan's blog\n\nVdoing主题开发者\n\n文渊博客\n\n不甘平庸的90后程序员\n\n- name: Evan's blog\n  desc: 'Vdoing主题开发者'\n  avatar: https://cdn.jsdelivr.net/gh/xugaoyi/image_store/blog/20200103123203.jpg\n  link: https://xugaoyi.com/\n  bgColor: '#FFFBF0'\n  textColor: '#A05F2C'\n- name: 文渊博客\n  desc: '不甘平庸的90后程序员'\n  avatar: https://www.wenyuanblog.com/favicon.png\n  link: https://www.wenyuanblog.com/\n  bgColor: '#FFFBF0'\n  textColor: '#A05F2C'\n\n\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n",
      "normalizedContent": "# 精选知识库\n\nawesome-bookmarks\n\n个人收藏夹\n\n阮一峰的网络日志\n\n较为详细的前端知识教程\n\n- name: awesome-bookmarks\n  desc: 个人收藏夹\n  avatar: https://panjiachen.github.io/awesome-bookmarks/home.jpg # 可选\n  link: https://panjiachen.github.io/awesome-bookmarks/ # 可选\n  bgcolor: '#dcf4ff' # 可选，默认var(--bodybg)。颜色值有#号时请添加单引号\n  textcolor: '#6854a1' # 可选，默认var(--textcolor)\n- name: 阮一峰的网络日志\n  desc: '较为详细的前端知识教程'\n  avatar: https://www.ruanyifeng.com/favicon.ico\n  link: https://www.ruanyifeng.com/blog/\n  bgcolor: '#dcf4ff'\n  textcolor: '#6854a1'\n\n\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n\n\n\n# web文档\n\nmdn\n\nweb技术权威文档\n\n- name: mdn\n  desc: 'web技术权威文档'\n  avatar: https://developer.mozilla.org/favicon-48x48.97046865.png\n  link: https://developer.mozilla.org/zh-cn/docs/web\n  bgcolor: '#fafafa'\n  textcolor: '#666666'\n\n\n1\n2\n3\n4\n5\n6\n\n\n\n# 博客收录\n\nevan's blog\n\nvdoing主题开发者\n\n文渊博客\n\n不甘平庸的90后程序员\n\n- name: evan's blog\n  desc: 'vdoing主题开发者'\n  avatar: https://cdn.jsdelivr.net/gh/xugaoyi/image_store/blog/20200103123203.jpg\n  link: https://xugaoyi.com/\n  bgcolor: '#fffbf0'\n  textcolor: '#a05f2c'\n- name: 文渊博客\n  desc: '不甘平庸的90后程序员'\n  avatar: https://www.wenyuanblog.com/favicon.png\n  link: https://www.wenyuanblog.com/\n  bgcolor: '#fffbf0'\n  textcolor: '#a05f2c'\n\n\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n",
      "charsets": {
        "cjk": true
      }
    },
    {
      "title": "基于Antd的列表字段显隐组件",
      "frontmatter": {
        "title": "基于Antd的列表字段显隐组件",
        "date": "2022-01-01T00:50:55.000Z",
        "permalink": "/pages/6a22b0/",
        "categories": [
          "前端",
          "React"
        ],
        "tags": [
          "公共组件",
          "Antd",
          "React"
        ]
      },
      "regularPath": "/01.%E5%89%8D%E7%AB%AF/01.React/01.%E5%9F%BA%E4%BA%8Eantd%E7%9A%84%E5%88%97%E8%A1%A8%E6%98%BE%E9%9A%90%E7%BB%84%E4%BB%B6.html",
      "relativePath": "01.前端/01.React/01.基于antd的列表显隐组件.md",
      "key": "v-510cd091",
      "path": "/pages/6a22b0/",
      "lastUpdated": "2022/01/01, 01:19:17",
      "headersStr": null,
      "content": "",
      "normalizedContent": "",
      "charsets": {}
    },
    {
      "title": "关于",
      "frontmatter": {
        "title": "关于",
        "permalink": "/about",
        "sidebar": false,
        "article": false,
        "date": "2021-06-29T11:27:20.000Z"
      },
      "regularPath": "/99.%E5%85%B3%E4%BA%8E/01.%E5%85%B3%E4%BA%8E.html",
      "relativePath": "99.关于/01.关于.md",
      "key": "v-669ad55b",
      "path": "/about/",
      "headers": [
        {
          "level": 3,
          "title": "📚 Blog",
          "slug": "📚-blog",
          "normalizedTitle": "📚 blog",
          "charIndex": 2
        },
        {
          "level": 3,
          "title": "🎨 Theme",
          "slug": "🎨-theme",
          "normalizedTitle": "🎨 theme",
          "charIndex": 103
        },
        {
          "level": 3,
          "title": "🐺 Me",
          "slug": "🐺-me",
          "normalizedTitle": "🐺 me",
          "charIndex": 207
        }
      ],
      "lastUpdated": "2022/01/01, 01:19:17",
      "headersStr": "📚 Blog 🎨 Theme 🐺 Me",
      "content": "# 📚 Blog\n\n这是一个程序相关知识整理，归纳，总结的个人网站\n\n * 公共组件封装，文档和一些没用的注释\n * loading...\n\n提示\n\n文章内容仅是我个人的小总结，如有误还请指正。\n\n\n# 🎨 Theme\n\n本站主题是 使用了 xugaoyi 根据 vuepress 改编的 Vdoing 主题，这是一款简洁高效的VuePress 知识管理&博客 主题。 想了解更多请点击详情。（推荐）\n\n\n# 🐺 Me\n\n习惯独处，不喜喧扰\n\n更新日志",
      "normalizedContent": "# 📚 blog\n\n这是一个程序相关知识整理，归纳，总结的个人网站\n\n * 公共组件封装，文档和一些没用的注释\n * loading...\n\n提示\n\n文章内容仅是我个人的小总结，如有误还请指正。\n\n\n# 🎨 theme\n\n本站主题是 使用了 xugaoyi 根据 vuepress 改编的 vdoing 主题，这是一款简洁高效的vuepress 知识管理&博客 主题。 想了解更多请点击详情。（推荐）\n\n\n# 🐺 me\n\n习惯独处，不喜喧扰\n\n更新日志",
      "charsets": {
        "cjk": true
      }
    },
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-4d8519b1",
      "path": "/archives/",
      "lastUpdated": "2022/01/01, 01:19:17",
      "headersStr": null,
      "content": "",
      "normalizedContent": "",
      "charsets": {}
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "renserve",
        "tagline": "程序相关知识整理，归纳，总结。",
        "bannerBg": "/img/th.jpg"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-1599a7dd",
      "path": "/",
      "lastUpdated": "2022/01/01, 01:19:17",
      "headersStr": null,
      "content": "",
      "normalizedContent": "",
      "charsets": {}
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-4ce3c1de",
      "path": "/categories/",
      "lastUpdated": "2022/01/01, 01:19:17",
      "headersStr": null,
      "content": "",
      "normalizedContent": "",
      "charsets": {}
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-bf7d299e",
      "path": "/tags/",
      "lastUpdated": "2022/01/01, 01:19:17",
      "headersStr": null,
      "content": "",
      "normalizedContent": "",
      "charsets": {}
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端",
        "link": "/front/"
      },
      {
        "text": "收藏",
        "link": "/pages/a8a2c8/"
      },
      {
        "text": "索引",
        "link": "/archives/",
        "items": [
          {
            "text": "分类",
            "link": "/categories/"
          },
          {
            "text": "标签",
            "link": "/tags/"
          },
          {
            "text": "归档",
            "link": "/archives/"
          }
        ]
      },
      {
        "text": "关于",
        "link": "/about/"
      }
    ],
    "sidebarDepth": 2,
    "logo": "/img/logo.jpg",
    "searchMaxSuggestions": 10,
    "lastUpdated": "上次更新",
    "docsDir": "docs",
    "editLinks": true,
    "editLinkText": "编辑",
    "sidebar": {
      "/00.目录页/": [
        [
          "01.前端.md",
          "前端",
          "/front"
        ]
      ],
      "catalogue": {
        "前端": "/front"
      },
      "/01.前端/": [
        {
          "title": "React",
          "collapsable": true,
          "children": [
            [
              "01.React/01.基于antd的列表显隐组件.md",
              "基于Antd的列表字段显隐组件",
              "/pages/6a22b0/"
            ]
          ]
        }
      ],
      "/08.收藏/": [
        [
          "01.网站.md",
          "网站",
          "/pages/a8a2c8/"
        ]
      ],
      "/99.关于/": [
        [
          "01.关于.md",
          "关于",
          "/about"
        ]
      ]
    },
    "author": {
      "name": "renserve",
      "link": "https://github.com/renserve/code"
    },
    "blogger": {
      "avatar": "/img/logo.jpg",
      "name": "renserve",
      "slogan": "虚心若愚，求知若渴"
    },
    "social": {},
    "footer": {},
    "htmlModules": {
      "homeSidebarB": "",
      "sidebarB": "<!-- 正方形 -->\n      <ins class=\"adsbygoogle\"\n          style=\"display:block\"\n          data-ad-client=\"ca-pub-7828333725993554\"\n          data-ad-slot=\"3508773082\"\n          data-ad-format=\"auto\"\n          data-full-width-responsive=\"true\"></ins>\n      <script>\n          (adsbygoogle = window.adsbygoogle || []).push({});\n      </script>",
      "pageT": "<!-- 固定100% * 90px可显示，max-height:90px未见显示-->\n     <ins class=\"adsbygoogle\"\n          style=\"display:inline-block;width:100%;max-height:90px\"\n          data-ad-client=\"ca-pub-7828333725993554\"\n          data-ad-slot=\"6625304284\"></ins>\n      <script>\n          (adsbygoogle = window.adsbygoogle || []).push({});\n      </script>",
      "pageB": "<!-- 横向自适应 -->\n      <ins class=\"adsbygoogle\"\n          style=\"display:block\"\n          data-ad-client=\"ca-pub-7828333725993554\"\n          data-ad-slot=\"6620245489\"\n          data-ad-format=\"auto\"\n          data-full-width-responsive=\"true\"></ins>\n      <script>\n          (adsbygoogle = window.adsbygoogle || []).push({});\n      </script>",
      "windowRB": "<!-- 固定160*160px -->\n      <ins class=\"adsbygoogle\"\n          style=\"display:inline-block;max-width:160px;max-height:160px\"\n          data-ad-client=\"ca-pub-7828333725993554\"\n          data-ad-slot=\"8377369658\"></ins>\n      <script>\n          (adsbygoogle = window.adsbygoogle || []).push({});\n      </script>\n      "
    }
  }
}